### ISSUE TITLE
kick off meeting

### ISSUE THREAD

**Issue by robbiten** [potifarfar-soft/dnd5e-digital-character#5]
I suggest a kick off meeting, either a physical one (perhaps over a beer in a pub?) or over skype (also perhaps over a beer). The agenda could be something like:

- Discussing and filling in the MVP
- Determining the working process here on github (e.g. who closes issues, merges pulls etc.) and inform everyone on ones own ambition level. 
- Deciding programming language

Thoughts? @Muthaias @fredrik-hjarner  @kforsgren

**Comment by Muthaias** [comment]
I think that's a great idea. My two cents goes towards Typescript + React for frontend and PHP as a backend. I would also like to suggest having two separate projects for frontend and backend since they really don't need to be intertwined.

Anyhow. Meeting to discuss this is a great idea. I am free evenings most weekdays and all day most Sundays.

**Comment by kforsgren** [comment]
Hmm, would not a web app create some extra problems like need for hosting? Not that it's super diffcult to achieve tho... I guess it would be nice with the extra features such as looking at each others characters...

I was imagining an app with only local storage capabilities and no backend or centralized DB.

Maybe my ambition-level is way lower though :P

**Comment by fredrik-hjarner** [comment]
> I was imagining an app with only local storage capabilities and no backend or centralized DB.

My first thoughts were the same. More complicated with backend. But on the other hand, if the player should be shared between a DM and a Player then some kind of server/backend must be used (right?).

What is my point... don't know

Pro with server:
1. as mentioned above
2. We are 4 people so we 4 on frontend might be overkill? Dividing it up on backend/frontend might be a good way to divide labor.

Pro without server:
1. Easier.
2. Less things can fuck up.
3. Stuff written in only one language and not several.. blub blub.

I think I am for dividing into server/client (backend/frontend)

**Comment by Muthaias** [comment]
You can always build a web app completely without backend using local storage in the browser. And I would suggest starting out this way which is also a reason to suggest separating the projects and mainly focusing on UX and core logics in this project.

And a web app can always be package as an android app if you feel like the stand alone features are important.
 
I agree that we should put main focus on the frontend but I think it is preferrable to design the app with ease of serialization in mind. This should make saving and loading less of a hassle and the save and load "module" can always implement an interface that could connect to a backend instead of local storage.

**Comment by Muthaias** [comment]
But these are things that we could discuss during the kick off meeting :)

**Comment by robbiten** [comment]
So a suggestion, what about a skype meeting thursday evening at 20.00? I would very much like to meet irl, but I'm feeling worse again, might even call in sick from work.

**Comment by Muthaias** [comment]
Thursday at 20.00 works for me.

**Comment by fredrik-hjarner** [comment]
Thursday does not work for me.

**Comment by robbiten** [comment]
friday 20:00...?

**Comment by Muthaias** [comment]
Works for me.

**Comment by fredrik-hjarner** [comment]
That wurkz!

**Comment by robbiten** [comment]
Friday at 20 it is! K joins at will.

**Comment by kforsgren** [comment]
Indeed, we shall see. Slept 3 hrs tonight due to baby cold. Hopefully she's better by friday

**Comment by robbiten** [comment]
Hope she'll get well soon! If you in spite of lack of sleep want to join, this looks like a good [solution](https://www.drugs.com/illicit/speed.html) @kforsgren

**Comment by fredrik-hjarner** [comment]
Been too stressed this week. I have to cancel :/ . I need to take weekend and sleep

**Comment by robbiten** [comment]
Ah, okey!
