### ISSUE TITLE
Create issues and milestones towards the MVP

### ISSUE THREAD

**Issue by Muthaias** [potifarfar-soft/dnd5e-digital-character#7]
We need to create issues which covers the functionality of the MVP. The issues should be organised in semi-realistic milestones. There should be enough milestones to allow for frequent celebration ;)

I'm going to look into this on friday evening if anyone is interested.

**Comment by Muthaias** [comment]
@kforsgren @fredrik-hjarner @robbiten

**Comment by robbiten** [comment]
Sounds good monsieur! I'll be a bit busy on Friday, but I was planning to start working on this project this weekend. I don't see any problems if you want to start and form milestones and issues today already. If you want company you can just send me a holler on skype on the weekend, preferably with a couple of hours notice so that I can round off whatever I'm doing or plan ahead.

**Comment by fredrik-hjarner** [comment]
Urgh, so tired today, but I can probably join on saturday sunday.
